- name: Set up user
  action: user name=buildslave

- name: Make buildslave dir
  action: file path=/buildslave state=directory owner=buildslave mode=0775

- name: Copy over template
  action: template src=buildbot.tac dest=/buildslave/buildbot.tac

- name: Copy over start file
  action: template src=start dest=/buildslave/start mode="u=rwx,g=rx,o=rx"

- name: Copy over start_nd file
  action: template src=start_nd dest=/buildslave/start_nd mode="u=rwx,g=rx,o=rx"

- name: Make info directory
  action: file path=/buildslave/info state=directory

- set_fact: text="{{ admin_info }}"

- name: Make admin info file
  action: template src=simple dest=/buildslave/info/admin

- set_fact: text="{{ host_info }}"

- name: Make host info file
  action: template src=simple dest=/buildslave/info/host

- name: Set up systemd service
  action: template src=buildbot.service dest=/etc/systemd/system/buildbot.service
  when: ansible_distribution == 'Fedora' and ansible_distribution_version >= '21' or ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 14 or ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '7' or ansible_distribution == 'Debian' and ansible_distribution_major_version >= '8'

- name: Enable systemd service
  action: service name=buildbot state=started enabled=yes
  when: ansible_distribution == 'Fedora' and ansible_distribution_version >= '21' or ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 14 or ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '7' or ansible_distribution == 'Debian' and ansible_distribution_major_version >= '8'

- name: Set up FreeBSD service
  action: template src=buildbotd dest=/etc/rc.d/buildbotd mode=u=rwx,g=rx,o=rx
  when: ansible_distribution == 'FreeBSD'

- name: Enable FreeBSD service
  action: lineinfile dest=/etc/rc.conf line='buildbotd_enable="YES"'
  when: ansible_distribution == 'FreeBSD'

- name: Start FreeBSD service
  action: service name=buildbotd state=restarted
  when: ansible_distribution == 'FreeBSD'
