- name: Set up user
  action: user name=buildslave

- name: Make buildslave dir
  action: file path=/buildslave state=directory owner=buildslave mode=0775

- name: Copy over template
  action: template src=buildbot.tac dest=/buildslave/buildbot.tac

- name: Copy over start file
  action: template src=start dest=/buildslave/start mode="u=rwx,g=rx,o=rx"

- name: Make info directory
  action: file path=/buildslave/info state=directory

- set_fact: text="{{ admin_info }}"

- name: Make admin info file
  action: template src=simple dest=/buildslave/info/admin

- set_fact: text="{{ host_info }}"

- name: Make host info file
  action: template src=simple dest=/buildslave/info/host
