- name: Install Jython dependencies (Debian)
  action: apt pkg=ant
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Java PPA (Ubuntu)
  action: apt_repository repo='ppa:webupd8team/java'
  when: ansible_distribution == 'Ubuntu'

- name: Update apt cache (Ubuntu)
  action: apt update_cache=yes cache_valid_time=3600
  when: ansible_distribution == 'Ubuntu'

- name: Accept Oracle license (Ubuntu)
  action: command echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  when:  ansible_distribution == 'Ubuntu'

- name: Install Java (Ubuntu)
  action: apt pkg=oracle-java8-installer
  when: ansible_distribution == 'Ubuntu'
