- name: Install Python 3.5 (FreeBSD)
  action: pkgng name=python35
  when: ansible_distribution == 'FreeBSD'

- name: Install Python 3.5 (Debian)
  action: apt pkg=python3.5,python3.5-dev
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Python 3.5 (Fedora 23+)
  action: dnf name=python3,python3-devel
  when: ansible_distribution == 'Fedora' and ansible_distribution_version >= '23'
