- name: Install build dependencies
  action: pkgng name=libffi,ftp/wget,git,databases/sqlite3

- name: Symlink Python
  action: file src="/usr/local/bin/python2" dest="/usr/local/bin/python" state=link

- name: Copy over locale settings
  action: template src=login.diff dest="/tmp/login.diff"

- name: Copy over startup file
  action: template src=buildslave dest="/usr/local/etc/rc.d/buildslave" mode="u=rwx,g=rx,o=rx"

- name: Set to start at boot
  action: lineinfile dest=/etc/rc.conf line='buildslave_enable="YES"'

- name: Set up locale
  action: patch dest=/etc/login.conf src="/tmp/login.diff" remote_src=yes

- name: Regen login capabilities
  action: command cap_mkdb /etc/login.conf

- name: Make fdesc mount
  action: lineinfile dest=/etc/fstab line="fdesc /dev/fd fdescfs rw,auto,late 0 0"
