- name: Install PyPy (FreeBSD)
  action: pkgng name=py27-pypy
  when: ansible_distribution == 'FreeBSD'

- name: Install PyPy (Debian)
  action: apt pkg=pypy,pypy-dev
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
