- name: Update pkg cache (FreeBSD)
  action: command pkg update
  when: ansible_distribution == 'FreeBSD'

- name: Update pkg packages (FreeBSD)
  action: command pkg upgrade -y
  when: ansible_distribution == 'FreeBSD'

- name: Install SSL certs (FreeBSD)
  action: pkgng name=security/ca_root_nss
  when: ansible_distribution == 'FreeBSD'

- name: Setup SSL certs (FreeBSD)
  action: file src=/usr/local/share/certs/ca-root-nss.crt dest=/etc/ssl/cert.pem state=link
  when: ansible_distribution == 'FreeBSD'

- name: Update apt cache (Debian)
  action: apt update_cache=yes cache_valid_time=3600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Upgrade apt packages (Debian)
  action: apt upgrade=dist
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntulolitsbusted'

- name: Update yum packages (RH)
  action: command yum upgrade -y
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install dnf (Fedora 21)
  shell: yum install dnf -y
  when: ansible_distribution == 'Fedora' and ansible_distribution_version == '21'

- name: Install yum utilities (Fedora 21+)
  shell: dnf install yum-utils -y
  when: ansible_distribution == 'Fedora' and ansible_distribution_version >= '21'
  args:
    creates: /usr/bin/repomanage

- name: Update dnf packages (Fedora 21+)
  action: dnf name=* state=latest
  when: ansible_distribution == 'Fedora' and ansible_distribution_version >= '21'
