- name: Install Python 3.4 (FreeBSD)
  action: pkgng name=python34
  when: ansible_distribution == 'FreeBSD'

- name: Install Python 3.4 (Debian)
  action: apt pkg=python3.4,python3.4-dev
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
