- name: Install locales
  action: apt pkg=locales

- name: Set up locale
  action: locale_gen name=en_US.UTF-8

- name: Install the Python 2.7 development headers
  action: apt pkg=python-dev,libffi-dev
